### ISSUE TITLE
links to download multiqc files seem to be broken

### ISSUE THREAD

**Issue by asaravia-butler** [J-81/dp_tools#32]
gitpod /workspace/dp_tools (metrics_extraction_subfeature) $ python download_multiqc_from_OSD.py --osd-id --output-dir
https://osdr.nasa.gov/genelab/data/glds/files/
Traceback (most recent call last):
  File "/workspace/dp_tools/download_multiqc_from_OSD.py", line 54, in <module>
    main()
  File "/home/gitpod/miniconda3/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/gitpod/miniconda3/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/gitpod/miniconda3/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/gitpod/miniconda3/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/workspace/dp_tools/download_multiqc_from_OSD.py", line 16, in main
    files = find_matching_filenames(accession=osd_id, filename_pattern=".*multiqc.*.zip")
  File "/workspace/dp_tools/dp_tools/glds_api/commons.py", line 56, in find_matching_filenames
    df = get_table_of_files(accession)
  File "/workspace/dp_tools/dp_tools/glds_api/commons.py", line 41, in get_table_of_files
    with urlopen(url) as response:
  File "/home/gitpod/miniconda3/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/home/gitpod/miniconda3/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/home/gitpod/miniconda3/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/home/gitpod/miniconda3/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/home/gitpod/miniconda3/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/home/gitpod/miniconda3/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: NOT FOUND

**Comment by asaravia-butler** [comment]
Looks like the example command just needs to be updated to require an OSD-#...
Is there a way to pull all OSD numbers that include RNAseq data without having to specify each one?
